version: 2
jobs:
  build:
    machine: true

    steps:
      - checkout
      - run:
            name: docker-compose up
            command: |
                 docker-compose -f /home/circleci/project/infrastructure/docker-compose.yml up -d
      - run:
          name: Run PHPUnit
          command: |
            cd /home/circleci/project/infrastructure
            docker-compose exec infrastructure_app ./vendor/bin/phpunit
        