version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.4.6-node-browsers
        environment:
          - APP_DEBUG: true
          - DB_CONNECTION: mysql
          - DB_DATABASE: laravel_local
          - DB_USERNAME: root
 
      - image: circleci/mysql:8.0.19-ram
        environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD: true
          - MYSQL_DATABASE: laravel_local
    
    steps:
      - checkout

      - run:
          name: Setup docker
          command: |
            cd /Applications/fish_restaurant/docker-laravel
            make remake
 
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-
 
              
      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor
 
      - run: docker-compose exec app ./vendor/bin/phpunit
