version: 2
jobs:
  build:
    machine: true

    environment:
      DB_CONNECTION: circle_testing
    
    steps:
      - checkout
      - run:
            name: docker-compose up
            command: |
              docker-compose -f /home/circleci/project/infrastructure/docker-compose.yml up -d --build
      - run:
            name: composer install
            command: |
              docker-compose -f /home/circleci/project/infrastructure/docker-compose.yml exec app composer install --dev
      - run:
            name: migrate
            command: |
              docker-compose -f /home/circleci/project/infrastructure/docker-compose.yml exec app php artisan migrate
    
      - run:
            name: seed
            command: |
              docker-compose -f /home/circleci/project/infrastructure/docker-compose.yml exec app php artisan db:seed


      - run:
          name: Run PHPUnit
          command: |
            docker-compose -f /home/circleci/project/infrastructure/docker-compose.yml exec app ./vendor/bin/phpunit
        