version: 2
jobs:
  build:
    machine: true

    steps:
      - checkout
      - run:
            name: docker-compose up
            command: |
                docker-compose -f /home/circleci/project/infrastructure/docker-compose.yml build --no-cache --force-rm
                docker-compose -f /home/circleci/project/infrastructure/docker-compose.yml up -d
      - run:
          name: Run PHPUnit
          command: |
            cd /home/circleci/project/infrastructure
            docker-compose ps 
            docker-compose image

            docker-compose -f /home/circleci/project/infrastructure/docker-compose.yml ps
            docker-compose -f /home/circleci/project/infrastructure/docker-compose.yml image
      - run:
          name: Run PHPUnit
          command: |
            docker-compose -f /home/circleci/project/infrastructure/docker-compose.yml exec infrastructure_app_1 ./vendor/bin/phpunit
        