version: 2
jobs:
  build:
    machine: true

    environment:
      DB_CONNECTION: circle_testing
    
    steps:
      - checkout
      - run:
            name: docker-compose up
            command: |
              docker-compose -f /home/circleci/project/infrastructure/docker-compose.yml up -d --build

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "/home/circleci/project/backend/composer.json" }}
            - v1-dependencies-

      - run:
            name: composer install
            command: |
              docker-compose -f /home/circleci/project/infrastructure/docker-compose.yml exec app composer install --dev
      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "/home/circleci/project/backend/composer.json" }}

      - run:
            name: migrate
            command: |
              docker-compose -f /home/circleci/project/infrastructure/docker-compose.yml exec app php artisan key:generate --env=testing
              docker-compose -f /home/circleci/project/infrastructure/docker-compose.yml exec app php artisan migrate:fresh --seed

    
      - run:
            name: seed
            command: |
              docker-compose -f /home/circleci/project/infrastructure/docker-compose.yml exec app php artisan db:seed


      - run:
          name: Run PHPUnit
          command: |
            docker-compose -f /home/circleci/project/infrastructure/docker-compose.yml exec app ./vendor/bin/phpunit
        