version: 2
jobs:
  build:
    docker:
      - image: sichimura/fish_restaurant
        auth:
          username: $DOCKERHUB_USER # 文字列リテラル値を指定するか
          password: $DOCKERHUB_PASSWORD 
    steps:
      - checkout

      - run:
          name: Setup docker
          command: |
            cd infrastructure
            mkdir -p ./docker/php/bash/psysh
            touch ./docker/php/bash/.bash_history
            ls -a
            docker login -u $DOCKER_USER -p $DOCKER_PASS 
            sudo docker-compose up -d --build
            sudo docker-compose exec app composer install
 
      - run:
          name: Setup Laravel
          command: |
            sudo docker-compose exec app cp .env.example .env
            sudo docker-compose run app php artisan key:generate
            sudo docker-compose exec app php artisan storage:link
            sudo docker-compose run app php artisan migrate:refresh --seed
 
      - run: sudo docker-compose exec app ./vendor/bin/phpunit
