version: 2
jobs:
  build:
    machine: true

    steps:
      - checkout
      - run:
            name: docker-compose up
            command: |
              docker-compose -f /home/circleci/project/infrastructure/docker-compose.yml up -d --build
      - run:
            name: Install PHP libraries
            command: |
              docker-compose -f /home/circleci/project/infrastructure/docker-compose.yml exec app composer install --dev
      - run:
          name: Run PHPUnit
          command: |
            docker-compose -f /home/circleci/project/infrastructure/docker-compose.yml exec app ./vendor/bin/phpunit
        